# Generated by Django 5.0.4 on 2025-10-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('CBE', 'CBE'), ('Telebirr', 'Telebirr'), ('Awash', 'Awash'), ('Dashin', 'Dashin'), ('Other', 'Other')], max_length=50)),
                ('account_number', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='api.restaurant')),
            ],
        ),
    ]
